"""
This type stub file was generated by pyright.
"""

cached_property = property
threaded_cached_property = property

class cached_property_with_ttl(property):
    """
    A property that is only computed once per instance and then replaces itself
    with an ordinary attribute. Setting the ttl to a number expresses how long
    the property will last before being timed out.
    """
    def __init__(self, ttl: float=...) -> None:
        ...
  
cached_property_ttl = cached_property_with_ttl
timed_cached_property = cached_property_with_ttl
class threaded_cached_property_with_ttl(cached_property_with_ttl):
    """
    A cached_property version for use in environments where multiple threads
    might concurrently try to access the property.
    """
    def __init__(self, ttl: float=...) -> None:
        ...
    
threaded_cached_property_ttl = threaded_cached_property_with_ttl
timed_threaded_cached_property = threaded_cached_property_with_ttl
