"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable
from haps.scopes import Scope

class SingletonScope(Scope):
    """
    Dependencies within SingletonScope are created only once in
    the application context.
    """
    _objects = ...
    def get_object(self, type_: Callable) -> Any:
        ...
    


