"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Type
from haps.config import Configuration

class Application:
    """
    Base Application class that should be the entry point for haps
    applications. You can override `__main__` to inject dependencies.
    """
    @classmethod
    def configure(cls, config: Configuration) -> None:
        """
        Method for configure haps application.

        This method is invoked before autodiscover.

        :param config: Configuration instance
        """
        ...
    
    def run(self) -> None:
        """
        Method for application entry point (like the `main` method in C).
        Must be implemented.
        """
        ...
    


class ApplicationRunner:
    @staticmethod
    def run(app_class: Type[Application], extra_module_paths: List[str] = ..., **kwargs: Any) -> None:
        """
        Runner for haps application.

        :param app_class: :class:`~haps.application.Application` type
        :param extra_module_paths: Extra modules list to autodiscover
        :param kwargs: Extra arguments are passed to\
                :func:`~haps.Container.autodiscover`
        """
        ...
    


