"""
This type stub file was generated by pyright.
"""

import asyncio

"""
Module ``helpers``
------------------

Helper functions and coroutines for :mod:`asynctest`.
"""
@asyncio.coroutine
def exhaust_callbacks(loop):
    """
    Run the loop until all ready callbacks are executed.

    The coroutine doesn't wait for callbacks scheduled in the future with
    :meth:`~asyncio.BaseEventLoop.call_at()` or
    :meth:`~asyncio.BaseEventLoop.call_later()`.

    :param loop: event loop
    """
    ...

